name: Deploy MIC ADMIN
on: push

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install

      - run: npm run build -- --deploy-url=https://storage.googleapis.com/mg-frontend/mic-admin-dev/ --output-path=dist/mic-admin-dev --base-href /mg-frontend/mic-admin-dev/ --configuration=mic-admin-dev

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
          export_default_credentials: true
      - name: Upload
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./dist
          destination: mg-frontend
          parent: false
      - name: Change Permissions
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=60" gs://mg-frontend/**/*
